import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Kamharida',
      email: 'kamharida007@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Nnamdi',
      email: 'agubiggest@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Kenstar Cooker 6090',
      slug: 'kenstar-cooker-6090',
      category: 'Gas Cookers',
      image: '/images/Kcooker1.jpeg',
      price: 70,
      brand: 'Kenstar',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Automatic igniter. Large oven capacity. 4 gas burners. Easy to clean. Durable',
      isFeatured: true,
      banner: '/images/Kcooker1.jpeg',
    },
    {
      name: 'LG Washing Machine 8kg',
      slug: 'lg-washing-machine-8kg',
      category: 'Washing Machines',
      image: '/images/Lwasher1.jpeg',
      price: 80,
      brand: 'LG',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: '8kg capacity. Easy to use. Durable. 2 years warranty.',
      isFeatured: true,
      banner: '/images/Lwasher1.jpeg',
    },
    {
      name: 'LG Refrigerator 392',
      slug: 'lg-refrigerator-392',
      category: 'Refrigerators',
      image: '/images/Lfridge1.jpeg',
      price: 90,
      brand: 'LG',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: '392 litres capacity. Frost free. Durable. 2 years warranty. Inverter compressor.',
    },
    {
      name: 'Hisense Freezer 260 ',
      slug: 'hisense-freezer-260',
      category: 'Freezers',
      image: '/images/Hfreezer1.jpeg',
      price: 90,
      brand: 'Hisense',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: '260 litres capacity. Frost free. Durable. 2 years warranty.',
    },
    {
      name: 'Senci Generator 4.1kva',
      slug: 'senci-generator-4.1kva',
      category: 'Generators',
      image: '/images/Sgenerator1.jpeg',
      price: 95,
      brand: 'Senci',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: '4.1kva. Easy to use. Durable. 2 years warranty.',
    },
    {
      name: 'Beko Cooker 6060',
      slug: 'beko-cooker-6060',
      category: 'Gas Cookers',
      image: '/images/Bcooker1.jpeg',
      price: 75,
      brand: 'Beko',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Quality cooker. 4 gas burners. Easy to clean. Durable',
    },
  ],
}

export default data